[install]
# Only install package versions published at least 7 days ago
minimumReleaseAge = 259200

minimumReleaseAgeExcludes = [
  "@types/bun",
  "typescript",
  "wrangler",
  "miniflare",
  "astro",
  "@astrojs/cloudflare",
  "@astrojs/internal-helpers",
  "@astrojs/markdown-remark",
  "@astrojs/mdx",
  "@astrojs/prism",
  "@astrojs/rss",
  "@astrojs/sitemap",
  "@astrojs/underscore-redirects",
  "workerd",
  "@cloudflare/workerd-darwin-arm64",
  "@cloudflare/workerd-darwin-64",
  "@cloudflare/workerd-linux-arm64",
  "@cloudflare/workerd-linux-64",
  "@cloudflare/workerd-windows-64",
]
