[tools]
bun = "1.3.3"
lefthook = "2.0.7"

[settings]
experimental = true
pin = true

[hooks]
postinstall = ["bun install", "lefthook install"]

[env]
_.path = "node_modules/.bin"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.preview]
run = "astro preview"

[tasks.astro]
run = "astro"

[tasks.fmt]
run = "prettier -wl ."

[tasks.test]
run = "vitest"

[tasks."test:ui"]
run = "vitest --ui"

[tasks.prefix-codes]
run = "bun scripts/prefix-codes.ts"

[tasks.deploy]
run = "wrangler deploy"
depends = ["build"]
