name = "just-be-dev"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public", "disable_nodejs_process_v2"]

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "micro-blog"
database_id = "cc5c17ec-ad2f-41b5-8d5c-cf542604c43b"
